### ISSUE TITLE
Feature Request: Update gradle-git version to latest

### ISSUE THREAD

**Issue by pgoodrich** [jdigger/gradle-defaults#22]
We are seeing a bug in `gradle-git 1.3.2` where the inferred version does not update to the latest tag.  This is reproduceable by all repo users.
For example, we have released version `1.14.0`, local repos are updated to latest master, and the inferred version for future builds remains at `1.13.1-dev` instead of `1.14.1-dev`

Unfortunately we do not know yet how it ended up in this corrupted state or an easy fix.  Deleting the release/tag and re-releasing `1.14.0` does not seem to fix the issue.

For now we are working around it but wanted to make you aware :smiley:

**Comment by jdigger** [comment]
Very odd. Thanks for the heads-up. Currently working on a major refactoring ( #13 ) and will do version updates soon after. (Including possibly making it so it can be easily independently versioned.)

**Comment by jdigger** [comment]
Is the "prior" version that it should be inferring from on the same linear branch as the current branch? Gradle-git scans back on the current branch to find the first tag it finds matching the pattern, so if the prior tag is on a sibling that may be causing the issue.

**Comment by pgoodrich** [comment]
Yes, the `1.13.0` tag was created on master and all branches including master started seeing the inferred version issue.  Though now that I'm thinking about it, I wonder if a force push to master could have triggered the issue even though the tags remained properly assigned.

**Comment by pgoodrich** [comment]
We started seeing a slightly different flavor of this issue related to cherry-picks.  The tags were being created on the release branch and obviously not being propagated back to the master branch.  As that is expected behavior with normal use cases, not an issue related to the plugin.

All that said, we haven't seen the original bug again so I think this can be closed as an issue.  Either way we appreciate the update you've made to the gradle-git version!

**Comment by jdigger** [comment]
Closing per @pgoodrich's comment. Thanks, Paul!
